import type {
  ChatSummary,
  ChatThread,
  Event,
  EventInterest,
  EventSummary,
  MatchSummary,
  UserProfile,
} from "@/types";

export const events: Event[] = [
  {
    id: "mlb-yankees-redsox-2026-05-06",
    title: "Yankees vs Red Sox",
    league: "MLB",
    teams: ["Yankees", "Red Sox"],
    date: "2026-05-06",
    time: "7:05 PM",
    venue: "Yankee Stadium",
    borough_or_area: "Bronx",
    average_ticket_price: 105,
    vibe: "high-energy",
    description: "Classic rivalry energy with loud innings and instant conversation starters.",
  },
  {
    id: "mlb-mets-phillies-2026-05-08",
    title: "Mets vs Phillies",
    league: "MLB",
    teams: ["Mets", "Phillies"],
    date: "2026-05-08",
    time: "7:10 PM",
    venue: "Citi Field",
    borough_or_area: "Queens",
    average_ticket_price: 78,
    vibe: "social",
    description: "Easygoing baseball night with plenty of time to talk between innings.",
  },
  {
    id: "nhl-rangers-devils-2026-05-10",
    title: "Rangers vs Devils",
    league: "NHL",
    teams: ["Rangers", "Devils"],
    date: "2026-05-10",
    time: "7:30 PM",
    venue: "Madison Square Garden",
    borough_or_area: "Manhattan",
    average_ticket_price: 160,
    vibe: "electric",
    description: "Fast pace and crowd roar make this ideal for bold first-date chemistry.",
  },
  {
    id: "nhl-islanders-hurricanes-2026-05-11",
    title: "Islanders vs Hurricanes",
    league: "NHL",
    teams: ["Islanders", "Hurricanes"],
    date: "2026-05-11",
    time: "7:00 PM",
    venue: "UBS Arena",
    borough_or_area: "Elmont",
    average_ticket_price: 122,
    vibe: "intense",
    description: "Playoff-style pressure and nonstop action for people who like adrenaline.",
  },
  {
    id: "nba-knicks-heat-2026-05-13",
    title: "Knicks vs Heat",
    league: "NBA",
    teams: ["Knicks", "Heat"],
    date: "2026-05-13",
    time: "8:00 PM",
    venue: "Madison Square Garden",
    borough_or_area: "Manhattan",
    average_ticket_price: 185,
    vibe: "premium",
    description: "Prime-time basketball and iconic arena atmosphere for statement date nights.",
  },
  {
    id: "nba-nets-celtics-2026-05-14",
    title: "Nets vs Celtics",
    league: "NBA",
    teams: ["Nets", "Celtics"],
    date: "2026-05-14",
    time: "7:30 PM",
    venue: "Barclays Center",
    borough_or_area: "Brooklyn",
    average_ticket_price: 98,
    vibe: "modern",
    description: "Music, lights, and a sleek downtown crowd make this a stylish meetup.",
  },
  {
    id: "wnba-liberty-aces-2026-05-16",
    title: "Liberty vs Aces",
    league: "WNBA",
    teams: ["Liberty", "Aces"],
    date: "2026-05-16",
    time: "7:00 PM",
    venue: "Barclays Center",
    borough_or_area: "Brooklyn",
    average_ticket_price: 64,
    vibe: "upbeat",
    description: "Fun, supportive crowd and elite hoops for a confident, easy first hang.",
  },
  {
    id: "mls-nycfc-atlanta-2026-05-17",
    title: "NYCFC vs Atlanta United",
    league: "MLS",
    teams: ["NYCFC", "Atlanta United"],
    date: "2026-05-17",
    time: "6:00 PM",
    venue: "Yankee Stadium",
    borough_or_area: "Bronx",
    average_ticket_price: 52,
    vibe: "chant-heavy",
    description: "Supporters' section chants and nonstop movement keep things playful.",
  },
  {
    id: "mls-redbulls-philly-2026-05-18",
    title: "Red Bulls vs Philadelphia Union",
    league: "MLS",
    teams: ["Red Bulls", "Philadelphia Union"],
    date: "2026-05-18",
    time: "7:30 PM",
    venue: "Sports Illustrated Stadium",
    borough_or_area: "Harrison",
    average_ticket_price: 46,
    vibe: "loud",
    description: "Rivalry match with supporter culture and easy conversation over shared chants.",
  },
  {
    id: "pwhl-ny-sirens-boston-2026-05-19",
    title: "New York Sirens vs Boston",
    league: "PWHL",
    teams: ["New York Sirens", "Boston"],
    date: "2026-05-19",
    time: "7:00 PM",
    venue: "Prudential Center",
    borough_or_area: "Newark",
    average_ticket_price: 38,
    vibe: "community-forward",
    description: "Affordable, high-skill hockey with a welcoming fan base and strong conversation flow.",
  },
];

export const profiles: UserProfile[] = [
  {
    id: "u1",
    first_name: "Avery",
    age: 29,
    city: "Brooklyn",
    favorite_teams: ["Liberty", "Nets"],
    bio: "Design lead, hoops obsessive, and always down for a halftime snack draft.",
    ticket_budget: 140,
    preferred_vibe: "upbeat",
    interested_event_ids: ["wnba-liberty-aces-2026-05-16", "nba-nets-celtics-2026-05-14"],
    intent: "relationship",
  },
  {
    id: "u2",
    first_name: "Marcus",
    age: 33,
    city: "Queens",
    favorite_teams: ["Mets", "Knicks"],
    bio: "Teacher by day, box score nerd by night. Loves loyal fan energy.",
    ticket_budget: 110,
    preferred_vibe: "social",
    interested_event_ids: ["mlb-mets-phillies-2026-05-08", "nba-knicks-heat-2026-05-13"],
    intent: "long_term",
  },
  {
    id: "u3",
    first_name: "Nia",
    age: 27,
    city: "Manhattan",
    favorite_teams: ["Rangers", "Yankees"],
    bio: "Consultant who values punctuality, playoff intensity, and witty banter.",
    ticket_budget: 220,
    preferred_vibe: "electric",
    interested_event_ids: ["nhl-rangers-devils-2026-05-10", "mlb-yankees-redsox-2026-05-06"],
    intent: "relationship",
  },
  {
    id: "u4",
    first_name: "Leo",
    age: 31,
    city: "Bronx",
    favorite_teams: ["Yankees", "NYCFC"],
    bio: "Product manager, extrovert, and firm believer in postgame dessert runs.",
    ticket_budget: 95,
    preferred_vibe: "high-energy",
    interested_event_ids: ["mlb-yankees-redsox-2026-05-06", "mls-nycfc-atlanta-2026-05-17"],
    intent: "casual",
  },
  {
    id: "u5",
    first_name: "Sofia",
    age: 30,
    city: "Hoboken",
    favorite_teams: ["Devils", "Red Bulls"],
    bio: "Architect who likes intense games and low-key bars after final whistle.",
    ticket_budget: 130,
    preferred_vibe: "intense",
    interested_event_ids: ["nhl-rangers-devils-2026-05-10", "mls-redbulls-philly-2026-05-18"],
    intent: "long_term",
  },
  {
    id: "u6",
    first_name: "Dante",
    age: 26,
    city: "Staten Island",
    favorite_teams: ["Islanders", "Mets"],
    bio: "Chef in training, sharp humor, and a thing for underdog comebacks.",
    ticket_budget: 85,
    preferred_vibe: "intense",
    interested_event_ids: ["nhl-islanders-hurricanes-2026-05-11", "mlb-mets-phillies-2026-05-08"],
    intent: "relationship",
  },
  {
    id: "u7",
    first_name: "Harper",
    age: 34,
    city: "Brooklyn",
    favorite_teams: ["Liberty", "Knicks"],
    bio: "Journalist, coffee loyalist, and fan of emotionally mature sports debates.",
    ticket_budget: 170,
    preferred_vibe: "premium",
    interested_event_ids: ["wnba-liberty-aces-2026-05-16", "nba-knicks-heat-2026-05-13"],
    intent: "long_term",
  },
  {
    id: "u8",
    first_name: "Cam",
    age: 28,
    city: "Long Island City",
    favorite_teams: ["Nets", "Islanders"],
    bio: "Fitness coach who likes spontaneous plans and energetic crowds.",
    ticket_budget: 120,
    preferred_vibe: "modern",
    interested_event_ids: ["nba-nets-celtics-2026-05-14", "nhl-islanders-hurricanes-2026-05-11"],
    intent: "casual",
  },
  {
    id: "u9",
    first_name: "Priya",
    age: 32,
    city: "Jersey City",
    favorite_teams: ["Red Bulls", "Sirens"],
    bio: "Startup ops lead who loves fan chants and long tactical breakdowns.",
    ticket_budget: 75,
    preferred_vibe: "loud",
    interested_event_ids: ["mls-redbulls-philly-2026-05-18", "pwhl-ny-sirens-boston-2026-05-19"],
    intent: "new_friends",
  },
  {
    id: "u10",
    first_name: "Julian",
    age: 35,
    city: "Astoria",
    favorite_teams: ["Mets", "NYCFC"],
    bio: "Film editor, patient listener, and always early to beat concession lines.",
    ticket_budget: 90,
    preferred_vibe: "chant-heavy",
    interested_event_ids: ["mlb-mets-phillies-2026-05-08", "mls-nycfc-atlanta-2026-05-17"],
    intent: "relationship",
  },
  {
    id: "u11",
    first_name: "Zoe",
    age: 25,
    city: "Lower Manhattan",
    favorite_teams: ["Rangers", "Liberty"],
    bio: "Grad student, naturally curious, and game for ambitious arena food picks.",
    ticket_budget: 100,
    preferred_vibe: "upbeat",
    interested_event_ids: ["nhl-rangers-devils-2026-05-10", "wnba-liberty-aces-2026-05-16"],
    intent: "casual",
  },
  {
    id: "u12",
    first_name: "Ethan",
    age: 30,
    city: "Williamsburg",
    favorite_teams: ["Yankees", "Knicks"],
    bio: "Engineer, playlist curator, and fan of authentic no-small-talk dates.",
    ticket_budget: 200,
    preferred_vibe: "premium",
    interested_event_ids: ["mlb-yankees-redsox-2026-05-06", "nba-knicks-heat-2026-05-13"],
    intent: "long_term",
  },
];

export const eventInterests: EventInterest[] = profiles.flatMap((profile) =>
  profile.interested_event_ids.map((eventId, index) => ({
    id: `interest-${profile.id}-${eventId}`,
    profile_id: profile.id,
    event_id: eventId,
    interest_level: index === 0 ? "high" : "medium",
    note: index === 0 ? "Top pick for this week." : undefined,
  })),
);

export const chatThreads: ChatThread[] = [
  {
    id: "thread-1",
    event_id: "mlb-yankees-redsox-2026-05-06",
    matched_profile_ids: ["u3", "u12"],
    messages: [
      {
        id: "msg-1",
        thread_id: "thread-1",
        sender_profile_id: "u3",
        text: "Want to meet by Gate 6 around 6:20?",
        sent_at: "2026-05-05T19:15:00Z",
      },
      {
        id: "msg-2",
        thread_id: "thread-1",
        sender_profile_id: "u12",
        text: "Perfect. I'll grab peanuts and save you a spot.",
        sent_at: "2026-05-05T19:17:00Z",
      },
    ],
  },
  {
    id: "thread-2",
    event_id: "wnba-liberty-aces-2026-05-16",
    matched_profile_ids: ["u1", "u7"],
    messages: [
      {
        id: "msg-3",
        thread_id: "thread-2",
        sender_profile_id: "u7",
        text: "Section 23 has great sightlines. Want those seats?",
        sent_at: "2026-05-12T21:02:00Z",
      },
      {
        id: "msg-4",
        thread_id: "thread-2",
        sender_profile_id: "u1",
        text: "Yes. And let's rate halftime songs after.",
        sent_at: "2026-05-12T21:06:00Z",
      },
    ],
  },
  {
    id: "thread-3",
    event_id: "mls-redbulls-philly-2026-05-18",
    matched_profile_ids: ["u5", "u9"],
    messages: [
      {
        id: "msg-5",
        thread_id: "thread-3",
        sender_profile_id: "u9",
        text: "Are you okay standing in the supporters section?",
        sent_at: "2026-05-16T14:50:00Z",
      },
      {
        id: "msg-6",
        thread_id: "thread-3",
        sender_profile_id: "u5",
        text: "Absolutely. I'll bring the scarf and the energy.",
        sent_at: "2026-05-16T14:56:00Z",
      },
    ],
  },
];

export const getEventById = (id: string) => events.find((event) => event.id === id);

export const getEvents = () => events;

export const getProfilesForEvent = (eventId: string) =>
  profiles.filter((profile) => profile.interested_event_ids.includes(eventId));

export const getChatThreadById = (id: string) => chatThreads.find((thread) => thread.id === id);

export const featuredEvents: EventSummary[] = events.map((event) => ({
  id: event.id,
  title: event.title,
  league: event.league,
  venue: event.venue,
  date: `${event.date} • ${event.time}`,
}));

export const starterMatches: MatchSummary[] = profiles.map((profile) => ({
  id: profile.id,
  name: `${profile.first_name}, ${profile.age}`,
  eventId: profile.interested_event_ids[0],
  vibe: profile.bio,
}));

export const starterChats: ChatSummary[] = chatThreads.map((thread) => {
  const counterpart = profiles.find((profile) => profile.id === thread.matched_profile_ids[0]);
  const lastMessage = thread.messages[thread.messages.length - 1];

  return {
    id: thread.id,
    matchId: thread.matched_profile_ids[0],
    name: counterpart?.first_name ?? "Match",
    teaser: lastMessage?.text ?? "Say hi to start the chat.",
  };
});
