import type {
  ChatSummary,
  ChatThread,
  Event,
  EventInterest,
  EventSummary,
  MatchSummary,
  UserProfile,
} from "@/types";

export const events: Event[] = [
  {
    id: "mlb-yankees-redsox-2026-04-17",
    title: "Yankees vs. Red Sox",
    league: "MLB",
    teams: ["Yankees", "Red Sox"],
    date: "2026-04-17",
    time: "7:05 PM",
    venue: "Yankee Stadium",
    borough_or_area: "Bronx",
    average_ticket_price: 118,
    vibe: "high-energy",
    description: "Big rivalry crowd and a fun Friday-night buzz.",
  },
  {
    id: "mlb-mets-phillies-2026-04-25",
    title: "Mets vs. Phillies",
    league: "MLB",
    teams: ["Mets", "Phillies"],
    date: "2026-04-25",
    time: "4:10 PM",
    venue: "Citi Field",
    borough_or_area: "Queens",
    average_ticket_price: 82,
    vibe: "social",
    description: "Day game pace with easy time to talk between innings.",
  },
  {
    id: "nhl-rangers-devils-2026-04-07",
    title: "Rangers vs. Devils",
    league: "NHL",
    teams: ["Rangers", "Devils"],
    date: "2026-04-07",
    time: "7:30 PM",
    venue: "Madison Square Garden",
    borough_or_area: "Manhattan",
    average_ticket_price: 174,
    vibe: "intense",
    description: "Fast game, loud building, and playoff-style tension.",
  },
  {
    id: "nhl-islanders-hurricanes-2026-04-09",
    title: "Islanders vs. Hurricanes",
    league: "NHL",
    teams: ["Islanders", "Hurricanes"],
    date: "2026-04-09",
    time: "7:30 PM",
    venue: "UBS Arena",
    borough_or_area: "Elmont",
    average_ticket_price: 128,
    vibe: "intense",
    description: "Physical hockey with a committed local crowd.",
  },
  {
    id: "nba-knicks-heat-2026-04-03",
    title: "Knicks vs. Heat",
    league: "NBA",
    teams: ["Knicks", "Heat"],
    date: "2026-04-03",
    time: "7:30 PM",
    venue: "Madison Square Garden",
    borough_or_area: "Manhattan",
    average_ticket_price: 198,
    vibe: "premium",
    description: "Prime matchup at MSG with classic NYC date-night energy.",
  },
  {
    id: "nba-nets-celtics-2026-04-12",
    title: "Nets vs. Celtics",
    league: "NBA",
    teams: ["Nets", "Celtics"],
    date: "2026-04-12",
    time: "6:00 PM",
    venue: "Barclays Center",
    borough_or_area: "Brooklyn",
    average_ticket_price: 112,
    vibe: "high-energy",
    description: "Big East Coast matchup and a lively Brooklyn crowd.",
  },
  {
    id: "wnba-liberty-aces-2026-06-06",
    title: "Liberty vs. Aces",
    league: "WNBA",
    teams: ["Liberty", "Aces"],
    date: "2026-06-06",
    time: "7:00 PM",
    venue: "Barclays Center",
    borough_or_area: "Brooklyn",
    average_ticket_price: 76,
    vibe: "high-energy",
    description: "Two top teams, packed house, and great arena atmosphere.",
  },
  {
    id: "mls-nycfc-atlanta-2026-05-30",
    title: "NYCFC vs. Atlanta United",
    league: "MLS",
    teams: ["NYCFC", "Atlanta United"],
    date: "2026-05-30",
    time: "7:30 PM",
    venue: "Yankee Stadium",
    borough_or_area: "Bronx",
    average_ticket_price: 58,
    vibe: "high-energy",
    description: "Supporter chants, quick pace, and a Saturday-night crowd.",
  },
  {
    id: "mls-redbulls-philly-2026-05-23",
    title: "Red Bulls vs. Philadelphia Union",
    league: "MLS",
    teams: ["Red Bulls", "Philadelphia Union"],
    date: "2026-05-23",
    time: "7:30 PM",
    venue: "Sports Illustrated Stadium",
    borough_or_area: "Harrison",
    average_ticket_price: 49,
    vibe: "high-energy",
    description: "Regional rivalry with nonstop chants in the lower bowl.",
  },
  {
    id: "pwhl-ny-sirens-boston-2026-01-24",
    title: "New York Sirens vs. Boston",
    league: "PWHL",
    teams: ["New York Sirens", "Boston"],
    date: "2026-01-24",
    time: "7:00 PM",
    venue: "Prudential Center",
    borough_or_area: "Newark",
    average_ticket_price: 42,
    vibe: "social",
    description: "Skilled hockey, friendly crowd, and affordable seats.",
  },
];

export const profiles: UserProfile[] = [
  {
    id: "u1",
    first_name: "Avery",
    age: 29,
    city: "Brooklyn",
    favorite_teams: ["Liberty", "Nets"],
    bio: "UX lead in Dumbo. I plan around tip-off.",
    ticket_budget: 145,
    preferred_vibe: "high-energy",
    interested_event_ids: ["wnba-liberty-aces-2026-06-06", "nba-nets-celtics-2026-04-12"],
    intent: "relationship",
  },
  {
    id: "u2",
    first_name: "Marcus",
    age: 33,
    city: "Queens",
    favorite_teams: ["Mets", "Knicks"],
    bio: "Middle-school teacher and lifelong Mets fan.",
    ticket_budget: 115,
    preferred_vibe: "social",
    interested_event_ids: ["mlb-mets-phillies-2026-04-25", "nba-knicks-heat-2026-04-03"],
    intent: "long_term",
  },
  {
    id: "u3",
    first_name: "Nia",
    age: 27,
    city: "Manhattan",
    favorite_teams: ["Rangers", "Yankees"],
    bio: "Healthcare consultant. Loves close games and dry humor.",
    ticket_budget: 230,
    preferred_vibe: "intense",
    interested_event_ids: ["nhl-rangers-devils-2026-04-07", "mlb-yankees-redsox-2026-04-17"],
    intent: "relationship",
  },
  {
    id: "u4",
    first_name: "Leo",
    age: 31,
    city: "Brooklyn",
    favorite_teams: ["Yankees", "NYCFC"],
    bio: "PM in fintech. Down for a quick drink before first pitch.",
    ticket_budget: 100,
    preferred_vibe: "high-energy",
    interested_event_ids: ["mlb-yankees-redsox-2026-04-17", "mls-nycfc-atlanta-2026-05-30"],
    intent: "casual",
  },
  {
    id: "u5",
    first_name: "Sofia",
    age: 30,
    city: "Hoboken",
    favorite_teams: ["Devils", "Red Bulls"],
    bio: "Architect in Hoboken. Big on smart banter and rivalry games.",
    ticket_budget: 135,
    preferred_vibe: "intense",
    interested_event_ids: ["nhl-rangers-devils-2026-04-07", "mls-redbulls-philly-2026-05-23"],
    intent: "long_term",
  },
  {
    id: "u6",
    first_name: "Dante",
    age: 26,
    city: "Jersey City",
    favorite_teams: ["Islanders", "Mets"],
    bio: "Line cook turned private chef. I never miss overtime.",
    ticket_budget: 90,
    preferred_vibe: "intense",
    interested_event_ids: ["nhl-islanders-hurricanes-2026-04-09", "mlb-mets-phillies-2026-04-25"],
    intent: "relationship",
  },
  {
    id: "u7",
    first_name: "Harper",
    age: 34,
    city: "Manhattan",
    favorite_teams: ["Liberty", "Knicks"],
    bio: "Politics reporter. Great seats and better conversation.",
    ticket_budget: 180,
    preferred_vibe: "premium",
    interested_event_ids: ["wnba-liberty-aces-2026-06-06", "nba-knicks-heat-2026-04-03"],
    intent: "long_term",
  },
  {
    id: "u8",
    first_name: "Cam",
    age: 28,
    city: "Brooklyn",
    favorite_teams: ["Nets", "Islanders"],
    bio: "Physical therapist in Park Slope. Last-minute plans work for me.",
    ticket_budget: 125,
    preferred_vibe: "high-energy",
    interested_event_ids: ["nba-nets-celtics-2026-04-12", "nhl-islanders-hurricanes-2026-04-09"],
    intent: "casual",
  },
  {
    id: "u9",
    first_name: "Priya",
    age: 32,
    city: "Jersey City",
    favorite_teams: ["Red Bulls", "Sirens"],
    bio: "Operations lead in health tech. Give me chants and tactics.",
    ticket_budget: 80,
    preferred_vibe: "social",
    interested_event_ids: ["mls-redbulls-philly-2026-05-23", "pwhl-ny-sirens-boston-2026-01-24"],
    intent: "new_friends",
  },
  {
    id: "u10",
    first_name: "Julian",
    age: 35,
    city: "Manhattan",
    favorite_teams: ["Mets", "NYCFC"],
    bio: "Commercial editor. Early train in, late game out.",
    ticket_budget: 95,
    preferred_vibe: "social",
    interested_event_ids: ["mlb-mets-phillies-2026-04-25", "mls-nycfc-atlanta-2026-05-30"],
    intent: "relationship",
  },
  {
    id: "u11",
    first_name: "Zoe",
    age: 25,
    city: "Brooklyn",
    favorite_teams: ["Rangers", "Liberty"],
    bio: "NYU grad student with a soft spot for MSG nights.",
    ticket_budget: 105,
    preferred_vibe: "high-energy",
    interested_event_ids: ["nhl-rangers-devils-2026-04-07", "wnba-liberty-aces-2026-06-06"],
    intent: "casual",
  },
  {
    id: "u12",
    first_name: "Ethan",
    age: 30,
    city: "Hoboken",
    favorite_teams: ["Yankees", "Knicks"],
    bio: "Software engineer. I always book aisle seats.",
    ticket_budget: 210,
    preferred_vibe: "premium",
    interested_event_ids: ["mlb-yankees-redsox-2026-04-17", "nba-knicks-heat-2026-04-03"],
    intent: "long_term",
  },
];

export const eventInterests: EventInterest[] = profiles.flatMap((profile) =>
  profile.interested_event_ids.map((eventId, index) => ({
    id: `interest-${profile.id}-${eventId}`,
    profile_id: profile.id,
    event_id: eventId,
    interest_level: index === 0 ? "high" : "medium",
    note: index === 0 ? "Top pick for this week." : undefined,
  })),
);

export const chatThreads: ChatThread[] = [
  {
    id: "thread-1",
    event_id: "mlb-yankees-redsox-2026-04-17",
    matched_profile_ids: ["u3", "u12"],
    messages: [
      {
        id: "msg-1",
        thread_id: "thread-1",
        sender_profile_id: "u3",
        text: "Want to meet by the Babe Ruth Plaza entrance at 6:15?",
        sent_at: "2026-04-15T22:15:00Z",
      },
      {
        id: "msg-2",
        thread_id: "thread-1",
        sender_profile_id: "u12",
        text: "Perfect. I'll be on the 4 train and can grab us waters on the way in.",
        sent_at: "2026-04-15T22:18:00Z",
      },
      {
        id: "msg-3",
        thread_id: "thread-1",
        sender_profile_id: "u3",
        text: "Deal. If lines are long, let's do Billy's after first pitch.",
        sent_at: "2026-04-15T22:20:00Z",
      },
    ],
  },
  {
    id: "thread-2",
    event_id: "wnba-liberty-aces-2026-06-06",
    matched_profile_ids: ["u1", "u7"],
    messages: [
      {
        id: "msg-4",
        thread_id: "thread-2",
        sender_profile_id: "u7",
        text: "I found two lower-bowl seats on the aisle. Want me to lock them in?",
        sent_at: "2026-06-02T20:42:00Z",
      },
      {
        id: "msg-5",
        thread_id: "thread-2",
        sender_profile_id: "u1",
        text: "Yes please. I'll get there early for tacos on Flatbush.",
        sent_at: "2026-06-02T20:46:00Z",
      },
      {
        id: "msg-6",
        thread_id: "thread-2",
        sender_profile_id: "u7",
        text: "Great. Let's meet by the Dean St entrance at 6:25.",
        sent_at: "2026-06-02T20:49:00Z",
      },
    ],
  },
  {
    id: "thread-3",
    event_id: "mls-redbulls-philly-2026-05-23",
    matched_profile_ids: ["u5", "u9"],
    messages: [
      {
        id: "msg-7",
        thread_id: "thread-3",
        sender_profile_id: "u9",
        text: "Are you good with PATH from Grove St? It's easiest for me.",
        sent_at: "2026-05-21T13:50:00Z",
      },
      {
        id: "msg-8",
        thread_id: "thread-3",
        sender_profile_id: "u5",
        text: "Yep, I'll hop on at Hoboken and bring an extra scarf.",
        sent_at: "2026-05-21T13:53:00Z",
      },
      {
        id: "msg-9",
        thread_id: "thread-3",
        sender_profile_id: "u9",
        text: "Amazing. Let's do section 133 so we can stand and sing.",
        sent_at: "2026-05-21T13:56:00Z",
      },
    ],
  },
];

export const getEventById = (id: string) => events.find((event) => event.id === id);

export const getEvents = () => events;

export const getProfilesForEvent = (eventId: string) =>
  profiles.filter((profile) => profile.interested_event_ids.includes(eventId));

export const getChatThreadById = (id: string) => chatThreads.find((thread) => thread.id === id);

export const featuredEvents: EventSummary[] = events.map((event) => ({
  id: event.id,
  title: event.title,
  league: event.league,
  venue: event.venue,
  date: `${event.date} • ${event.time}`,
}));

export const starterMatches: MatchSummary[] = profiles.map((profile) => ({
  id: profile.id,
  name: `${profile.first_name}, ${profile.age}`,
  eventId: profile.interested_event_ids[0],
  vibe: profile.bio,
}));

export const starterChats: ChatSummary[] = chatThreads.map((thread) => {
  const counterpart = profiles.find((profile) => profile.id === thread.matched_profile_ids[0]);
  const lastMessage = thread.messages[thread.messages.length - 1];

  return {
    id: thread.id,
    matchId: thread.matched_profile_ids[0],
    name: counterpart?.first_name ?? "Match",
    teaser: lastMessage?.text ?? "Say hi to start the chat.",
  };
});
